{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: logging
  name: {{ include "fluentd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fluentd.name" . }}
    helm.sh/chart: {{ include "fluentd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
{{- end -}}